language: php
php:
  - '7.0'
  - '7.1'

install:
  - mkdir -p app/etc var
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --prefer-dist --no-interaction --no-scripts --no-plugins

script:
  - ./vendor/bin/phpqa --ignoredDirs vendor,build --output cli --ansi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache